### ISSUE TITLE
Unable to use inline ephemeral volumes with non-Helm Chart Secret

### ISSUE THREAD

**Issue by datamattsson** [vast-data/vast-csi#12]
I need to use ephemeral volumes with separate secrets. I've tried multiple ways to provide the Secret to the inline volume construct without any rate of success.

```
...
  volumes:
  - csi:
      driver: csi.vastdata.com
      volumeAttributes:
        csi.storage.k8s.io/ephemeral: "true"
        eph_volume_name_fmt: csi:{namespace}:{name}:{id}
        inline-volume-secret-name: vast-file-backend
        inline-volume-secret-namespace: vast-storage
        root_export: /export
        secretName: vast-file-backend
        secretNamespace: vast-storage
        view_policy: my-view
        vip_pool_name: my-pool
        volume_name_fmt: csi:{namespace}:{name}:{id}
 ...
 ```
 
 or:
 
 ```
 ...
   volumes:
  - csi:
      driver: csi.vastdata.com
      volumeAttributes:
        csi.storage.k8s.io/controller-expand-secret-name: vast-file-backend
        csi.storage.k8s.io/controller-expand-secret-namespace: vast-storage
        csi.storage.k8s.io/controller-publish-secret-name: vast-file-backend
        csi.storage.k8s.io/controller-publish-secret-namespace: vast-storage
        csi.storage.k8s.io/ephemeral: "true"
        csi.storage.k8s.io/node-publish-secret-name: vast-file-backend
        csi.storage.k8s.io/node-publish-secret-namespace: vast-storage
        csi.storage.k8s.io/provisioner-secret-name: vast-file-backend
        csi.storage.k8s.io/provisioner-secret-namespace: vast-storage
        eph_volume_name_fmt: csi:{namespace}:{name}:{id}
        root_export: /export
        view_policy: kubernetes
        vip_pool_name: my-pool
        volume_name_fmt: csi:{namespace}:{name}:{id}
...
```

The error seems to be that the content in the `Secret` can't be looked up:

```
  Warning  FailedMount  90s (x15 over 9m37s)  kubelet  (combined from similar events): MountVolume.SetUp failed for volume "my-volume-1" : rpc error: code = Unknown desc = Exception calling application: Could not find username.
    field = username
    tip = Make sure username is present in secret.
    timestamp = 2024-09-17T18:55:51.246849
```

If I specify `secretName` in Helm values AND `endpoint` (even if the Secret contains endpoint) it works as expected.
