### ISSUE TITLE
Driver allows volumeMode: Block when it shouldn't.

### ISSUE THREAD

**Issue by datamattsson** [vast-data/vast-csi#19]
CSI e2e tests failures:

```
External Storage [Driver: csi.vastdata.com] [Testpattern: Dynamic PV (block volmode)] volumeMode should fail in binding dynamic provisioned PV to PVC [Slow] [LinuxOnly]
```

Attached are the e2e files. 

driver.yaml
```yaml
ShortName: vastdata
StorageClass:
  FromFile: "storage-class-vastdata.yaml"
SnapshotClass:
  FromFile: "volume-snapshot-class-vastdata.yaml"
DriverInfo:
  Name: csi.vastdata.com
  RequiredAccessModes:
    - ReadWriteMany
  Capabilities:
    nodeExpansion: true
    pvcDataSource: true
    controllerExpansion: true
    singleNodeVolume: true
    fsGroup: false
    persistence: true
    block: false
    exec: true
    snapshotDataSource: true
    multipods: true
    volumeLimits: false
    topology: false
    RWX: true
    FSResizeFromSourceNotSupported: true
    readWriteOncePod: false
  SupportedSizeRange: 
    Min: 4Gi 
    Max: 32Gi
```
storage-class-vastdata.yaml
```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
  name: vast-e2e
parameters:
  csi.storage.k8s.io/provisioner-secret-name: vast-file-backend
  csi.storage.k8s.io/provisioner-secret-namespace: vast-storage
  csi.storage.k8s.io/controller-publish-secret-name: vast-file-backend
  csi.storage.k8s.io/controller-publish-secret-namespace: vast-storage
  csi.storage.k8s.io/node-publish-secret-name: vast-file-backend
  csi.storage.k8s.io/node-publish-secret-namespace: vast-storage
  csi.storage.k8s.io/controller-expand-secret-name: vast-file-backend
  csi.storage.k8s.io/controller-expand-secret-namespace: vast-storage
  root_export: /mmattsson
  view_policy: mmattsson
  vip_pool_name: mmattsson
provisioner: csi.vastdata.com
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
mountOptions:
  - nfsvers=3
```
volume-snapshot-class-vastdata.yaml
```yaml
apiVersion: snapshot.storage.k8s.io/v1
deletionPolicy: Delete
driver: csi.vastdata.com
kind: VolumeSnapshotClass
metadata:
  name: vastdata-e2e
parameters:
  csi.storage.k8s.io/snapshotter-secret-name: vast-file-backend
  csi.storage.k8s.io/snapshotter-secret-namespace: vast-storage
  csi.storage.k8s.io/snapshotter-list-secret-name: vast-file-backend
  csi.storage.k8s.io/snapshotter-list-secret-namespace: vast-storage
```
